# Schema for the configuration files of the errorstyle module.

errorstyle.settings:
  type: config_object
  label: 'ErrorStyle settings'
  mapping:
    disable_inline_form_errors:
      type: integer
      label: 'Disable Inline Form Errors'
